version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver:latest
    hostname: axonserver
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=TRUE
    ports:
      - '8024:8024'
      - '8124:8124'
    networks:
      - giftcard-demo-network
  mongodb:
    image: bitnami/mongodb:6.0.6
    ports:
      - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - giftcard-demo-network
  synapse:
    build:
      context: synapse
    ports:
      - "8081:8081"
    networks:
      - giftcard-demo-network

networks:
  giftcard-demo-network: